project_id = "giuewshketieoddytowc"

[functions.submit-quote]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-deliverable-notification]
verify_jwt = false

[functions.get-user-by-email]
verify_jwt = true

[functions.get-user-by-id]
verify_jwt = true

[functions.assign-admin-role]
verify_jwt = true