// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://giuewshketieoddytowc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpdWV3c2hrZXRpZW9kZHl0b3djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODY0NzUsImV4cCI6MjA2OTQ2MjQ3NX0.luadBYyJm0HWHBJQ1yzihX8sC_3HGeE1t6XyL12hJvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});